FROM godot-videodecoder-ubuntu-bionic:latest

WORKDIR /opt/godot-videodecoder/ffmpeg-static
COPY ./ffmpeg-static .

ENV FINAL_TARGET_DIR=/opt/target
ENV THIRDPARTY_DIR=/opt/godot-videodecoder/thirdparty
ENV PLUGIN_BIN_DIR=/opt/godot-videodecoder/bin
ARG JOBS=1


RUN ./build.sh -d -p win32
RUN ./build.sh -B -p win32 -T "$THIRDPARTY_DIR/win32" -j $JOBS
WORKDIR /opt/godot-videodecoder

COPY . .
RUN scons -c platform=win32

RUN scons platform=win32 prefix="${FINAL_TARGET_DIR}"

